modules/Pupil/models/Pupil.php
<?php

namespace app\modules\Pupil\models;

use app\models\User\User;
use app\modules\Account\models\Account;
use Yii;
use app\modules\Clasa\models\Clasa;

/**
 * This is the model class for table "Pupil".
 *
 * @property integer $ID
 * @property integer $ClasaID
 * @property string $FirstName
 * @property string $LastName
 * @property string $BirthDate
 * @property string $Gender
 * @property string $Phone
 * @property string $Email
 * @property string $Address
 * @property string $Status
 *
 * @property Clasa $clasa
 */
class Pupil extends \yii\db\ActiveRecord
{
    
    const StatusActive = 'Active';
    const StatusInactive = 'Inactive';
    
    const GenderM = 'M';
    const GenderF = 'F';
    public $event;

    public static function getStatusList($addEmptyValue = false)
    {
        $result = $addEmptyValue ? ['' => '-'] : [];
        
        $result += [
            self::StatusActive => 'Active',
            self::StatusInactive => 'Inactive',
        ];
        
        return $result;
    }
    
    public static function getGenderList($addEmptyValue = false)
    {
        return \app\components\Enums\Gender::getList($addEmptyValue);
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'Pupil';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ClasaID'], 'integer'],
            ['ClasaID', 'default', 'value' => NULL],
            ['Status', 'default', 'value' => self::StatusActive],
            [['FirstName', 'LastName', 'BirthDate', 'Gender', 'Status'], 'required'],
            [['BirthDate'], 'safe'],
            [['FirstName', 'LastName', 'Phone', 'Email', 'Address'], 'string', 'max' => 255],
            [['Gender', 'Status'], 'string', 'max' => 20],
            [['ClasaID'], 'exist', 'skipOnError' => true, 'targetClass' => Clasa::className(), 'targetAttribute' => ['ClasaID' => 'ID']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'ID' => Yii::t('app', 'ID'),
            'ClasaID' => Yii::t('app', 'Clasa ID'),
            'FirstName' => Yii::t('app', 'First Name'),
            'LastName' => Yii::t('app', 'Last Name'),
            'BirthDate' => Yii::t('app', 'Birth Date'),
            'Gender' => Yii::t('app', 'Gender'),
            'Phone' => Yii::t('app', 'Phone'),
            'Email' => Yii::t('app', 'Email'),
            'Address' => Yii::t('app', 'Address'),
            'Status' => Yii::t('app', 'Status'),
        ];
    }
    
    public function beforeSave($insert)
    {
        parent::beforeSave($insert);
        
        $this->BirthDate = date('c', strtotime($this->BirthDate));
        
        return true;
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
        if ($this->event == 'add') {
            if (!$this->Email) {
                $this->Email = strtolower($this->FirstName) . '' . strtolower($this->LastName);
            }
//      Create user account for PUPIL
            $user = new User();
            $user->Email = $this->Email;
            $user->Type = 'Pupil';
            $user->Name = $this->FirstName . ' ' . $this->LastName;
            $user->Status = 'Active';
            $user->Password = substr(hash('sha512', rand()), 0, 8);
            $user->AuthKey = $user->Password;
            $user->EntityID = $this->ID;
            $user->save();
            $account = new Account();
            $account->PupilID = $user->EntityID;
            $account->UserID = $user->ID;
            $account->save();
//     create user account for parent
            $userp = new User();
            $userp->Email = $this->Email;
            $userp->Type = 'Parent';
            $userp->Name = $this->LastName;
            $userp->Status = 'Active';
            $userp->Password = substr(hash('sha512', rand()), 0, 8);
            $userp->AuthKey = $userp->Password;
            $userp->EntityID = $this->ID;
            $userp->save();
            $accountp = new Account();
            $accountp->PupilID = $userp->EntityID;
            $accountp->UserID = $userp->ID;
            $accountp->save();
        }
    }

    public function getClasa()
    {
        return $this->hasOne(Clasa::className(), ['ID' => 'ClasaID']);
    }
    
    public function getNiceDate()
    {
        return date(Yii::$app->params['date']['displayDateFormat'], strtotime($this->BirthDate));
    }
    
    public function getFullName()
    {
        return $this->FirstName . ' ' . $this->LastName;
    }
    
}

modules/Pupil/controllers/PupilController.php
<?php

namespace app\modules\Pupil\controllers;

use app\models\User\User;
use Yii;
use app\modules\Pupil\models\Pupil;
use app\modules\Pupil\models\PupilSearch;
use app\modules\Pupil\controllers\DefaultController;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\modules\Clasa\models\Clasa;

/**
 * PupilController implements the CRUD actions for Pupil model.
 */
class PupilController extends DefaultController
{
    public $parsed = [];
    public $skiped = [];

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Pupil models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PupilSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Pupil model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Pupil model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Pupil();
        $model->event = 'add';
        $classes = Clasa::find()->where(['Status' => Clasa::StatusActive])->indexBy('ID')->all();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {

            Yii::$app->session->setFlash('success', 'Date salvate');
            return $this->redirect(['update', 'id' => $model->ID]);
        } else {
            return $this->render('create', [
                'model' => $model,
                'classes' => $classes,
            ]);
        }
    }

    /**
     * Updates an existing Pupil model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        
        $classes = Clasa::find()->where(['Status' => Clasa::StatusActive])->indexBy('ID')->all();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', 'Date salvate');
            return $this->redirect(['index', 'id' => $model->ID]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'classes' => $classes,
            ]);
        }
    }

    /**
     * Deletes an existing Pupil model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Pupil model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Pupil the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Pupil::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionImport()
    {   $classes = Clasa::getClassesList($addEmptyValue = false);

        if (Yii::$app->request->isPost)
        {

            if (($handle = fopen($_FILES['File']['tmp_name'], "r")) !== FALSE)
            {
                $i = 0;
                while (($data = fgetcsv($handle)) !== FALSE && $i != 2)
                {
                    if ($i != 0) {
                        $this->parseRow($data,$classes);
                    }

                    $i++;
                }
                fclose($handle);
            }
        }

        return $this->render('import', [
            'parsed' => $this->parsed,
        ]);
    }

    private function parseRow($data,$classes)
    {

//    getting the classID
        $classNR = trim($data[14]);
        $classLetter = trim($data[15]);
        $clasa = $classNR.''.strtoupper($classLetter);
        $classID = '';
        foreach ($classes as $key => $class){
            if ($clasa == $class){
                $classID = (int)$key;
            }
        }
//    getting classID
//**********************************************************
//        getting birth date

        $name = explode(' ',$data[1]);
        $fname = trim($name[1]);
        $lname = trim($name[0]);
        $email = trim($data[35]);
        $birthDate = $data[8].'-'.$data[9].'-'.$data[10];
        $gender = strtoupper($data[2]);
        $learnLang2 = strtoupper($data[4]);
        $phone = $data[21];
        $address = $data[24].', str. '.$data[25].' '.$data[26].', ap.'.$data[27];

            $model = new Pupil();
            $model->BirthDate = $birthDate;
            $model->Gender = $gender;
            $model->FirstName = $fname;
            $model->LastName = $lname;
            $model->Status = 'Active';
            $model->ClasaID = $classID;
            $model->Email = $email;
            $model->LearnLang2 = $learnLang2;
            $model->Phone = $phone;
            $model->Address = $address;
            $model->event = 'add';

        if($model->save(false)){
            $this->parsed[] = $model->ID;
        }else{

        }
    }
}

modules/Pupil/views/pupil/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\modules\Clasa\models\Clasa;
use app\components\CDatepicker\CDatepicker;
use app\modules\Pupil\models\Pupil;

/* @var $this yii\web\View */
/* @var $model app\modules\Pupil\models\Pupil */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="pupil-form">

    <?php $form = ActiveForm::begin(); ?>
    
    <div class="row">
        <div class="col-md-2">
            <?= $form->field($model, 'FirstName')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-2">
            <?= $form->field($model, 'LastName')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-2">
            <?= $form->field($model, 'BirthDate')->widget(CDatepicker::className(), [
                'options' => [
                    'value' => empty($model->BirthDate) ? date('d.m.Y') : $model->NiceDate
                ]
            ]) ?>
        </div>
        <div class="col-md-1">
            <?= $form->field($model, 'Gender')->dropDownList(Pupil::getGenderList(true)) ?>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-2">
            <?= $form->field($model, 'ClasaID')->dropDownList(Clasa::getClassesList(true)) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <?= $form->field($model, 'Phone')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-2">
            <?= $form->field($model, 'Email')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'Address')->textInput(['maxlength' => true]) ?>
        </div>
    </div>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/Pupil/views/pupil/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\Pupil\models\PupilSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="pupil-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'ID') ?>

    <?= $form->field($model, 'ClasaID') ?>

    <?= $form->field($model, 'FirstName') ?>

    <?= $form->field($model, 'LastName') ?>

    <?= $form->field($model, 'BirthDate') ?>

    <?php // echo $form->field($model, 'Gender') ?>

    <?php // echo $form->field($model, 'Phone') ?>

    <?php // echo $form->field($model, 'Email') ?>

    <?php // echo $form->field($model, 'Address') ?>

    <?php // echo $form->field($model, 'Status') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/Pupil/views/pupil/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\modules\Pupil\models\Pupil */

$this->title = Yii::t('app', 'Create Pupil');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Pupils'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pupil-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'classes' => $classes,
    ]) ?>

</div>

modules/Pupil/views/pupil/import.php
<?php

    use yii\helpers\Html;
    use yii\widgets\ActiveForm;
    use kartik\file\FileInput;
    use yii\helpers\Url;
    use yii\widgets\Pjax;


$this->title = Yii::t('app', 'Import {modelClass}: ', [
    'modelClass' => 'Pupil',
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Pupil'), 'url' => ['index']];
$this->params['breadcrumbs'][] = Yii::t('app', 'Import');
?>
<div class="pupil-update">

    <h1><?= Html::encode($this->title) ?></h1>
<br/>

<?php $form = ActiveForm::begin([
    'options' => [
        'enctype' => 'multipart/form-data'
    ]
]); ?>
    <?php
    if($parsed){
        $pupils = [];
        foreach ($parsed as $id){
            $pupils[] = \app\modules\Pupil\models\Pupil::findOne($id);

        }?>
        <h2>Imported pupils</h2>
        <div class="row">
            <div class="col-md-1">Nr.</div>
            <div class="col-md-1">Nume</div>
            <div class="col-md-1">Prenume</div>
            <div class="col-md-1">Email</div>
            <div class="col-md-1">Clasa</div>
            <div class="col-md-1">Limba Straina</div>
            <div class="col-md-1">Data Nasterii</div>
            <div class="col-md-1">Sex</div>
            <div class="col-md-1">Status</div>
            <div class="col-md-1">Telefon</div>
            <div class="col-md-2">Adresa</div>
        </div><hr>
        <?php
        foreach ($pupils as $key => $pupil){
            ?>

        <div class="row">
            <div class="col-md-1">#<?=$key+1?></div>
            <div class="col-md-1"><?=$pupil->FirstName?></div>
            <div class="col-md-1"><?=$pupil->LastName?></div>
            <div class="col-md-1"><?=$pupil->Email?></div>
            <div class="col-md-1"><?=$pupil->clasa->fullName?></div>
            <div class="col-md-1"><?=$pupil->LearnLang2?></div>
            <div class="col-md-1"><?=$pupil->BirthDate?></div>
            <div class="col-md-1"><?=$pupil->Gender?></div>
            <div class="col-md-1"><?=$pupil->Status?></div>
            <div class="col-md-1"><?=$pupil->Phone?></div>
            <div class="col-md-2"><?=$pupil->Address?></div>
        </div><hr>
    <?php

        }
    }
    ?>
    <br/>
    <div class="row">
        <div class="col-md-4">
            <?= FileInput::widget([
                'name' => 'File',
                'attribute' => 'File',
                'options' => ['multiple' => false],
                'pluginOptions' => [
                    'allowedFileExtensions' => ['csv'],
                    'maxFileCount' => 1,
                    'showRemove' => false,
                    'showUpload' => false,
                ]
            ]); ?>
        </div>
    </div>
    <br />
    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Import'), ['class' => 'btn btn-danger']); ?>
    </div>

<?php ActiveForm::end(); ?>

</div>

modules/Pupil/views/pupil/index.php
<?php

use yii\helpers\Html;
use app\components\CGridView\CGridView;
use yii\widgets\Pjax;
use app\components\CDatepicker\CDatepicker;
use app\modules\Pupil\models\Pupil;
use app\modules\Clasa\models\Clasa;

/* @var $this yii\web\View */
/* @var $searchModel app\modules\Pupil\models\PupilSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Pupils');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pupil-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a(Yii::t('app', 'Create Pupil'), ['create'], ['class' => 'btn btn-success']) ?>
        <?= Html::a(Yii::t('app', 'Import'), ['import'], ['class' => 'btn btn-danger']) ?>
    </p>

<?php Pjax::begin(); ?>    
    <?= CGridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'ID',=
            'FirstName',
            'LastName',
            [
                'attribute' => 'BirthDate',
                'value' => function($model)
                {
                    return $model->NiceDate;
                },
                'filter' => CDatepicker::widget([
                    'model' => $searchModel,
                    'attribute' => 'BirthDate'
                ]),
                'options' => [
                    'style' => 'width:220px;'
                ]
            ],
            [
                'attribute' => 'Gender',
                'value' => function($model)
                {
                    return $model->Gender;
                },
                'filter' => Html::activeDropDownList($searchModel, 'Gender', Pupil::getGenderList(true), ['class' => 'form-control']),
            ],
            [
                'label' => 'Clasa',
                'value' => function($model)
                {
                    return $model->clasa->Number . $model->clasa->Letter;
                },
                'filter' => Html::activeDropDownList($searchModel, 'ClasaID', Clasa::getClassesList(true), ['class' => 'form-control pull-left', 'style' => 'width:50%']),
                'options' => [
                    'style' => 'width: 200px;'
                ],
            ],
            'Phone',
            'Email:email',
            // 'Address',
            // 'Status',

            [
                'class' => 'app\components\CGridView\CActionColumn'
            ],
        ],
    ]); ?>
<?php Pjax::end(); ?></div>

modules/Pupil/views/pupil/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\modules\Pupil\models\Pupil */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
    'modelClass' => 'Pupil',
]) . $model->ID;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Pupils'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->ID, 'url' => ['view', 'id' => $model->ID]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="pupil-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'classes' => $classes,
    ]) ?>

</div>

modules/Pupil/views/pupil/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\modules\Pupil\models\Pupil */

$this->title = $model->ID;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Pupils'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pupil-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->ID], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->ID], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'ID',
            'ClasaID',
            'FirstName',
            'LastName',
            'BirthDate',
            'Gender',
            'Phone',
            'Email:email',
            'Address',
            'Status',
        ],
    ]) ?>

</div>